spring.application.name=embabel-mcp
server.port=9090

# LLM Providers Configuration
groq.model=llama-3.1-8b-instant
groq.api.key=${GROQ_API_KEY:}
ollama.model=llama3
ollama.url=http://localhost:11434/api/generate